import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DesktopSidebar } from "@/components/desktop-sidebar";
import { MobileNav } from "@/components/mobile-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <div className="flex min-h-screen">
          {/* Desktop Sidebar - Hidden on mobile */}
          <DesktopSidebar />

          {/* Main Content Area */}
          <main className="flex-1 pb-20 md:pb-0 overflow-y-auto h-screen">
            {children}
          </main>

          {/* Mobile Bottom Nav - Hidden on desktop */}
          <MobileNav />
        </div>
      </body>
    </html>
  );
}
